### ISSUE TITLE
Florence_dataset_WorldCoordinates.txt 

### ISSUE THREAD

**Issue by tiredDi** [yongqyu/st-gcn-pytorch#1]
Thanks for your sharing
I have some confuse about the file: Florence_dataset_WorldCoordinates.txt 
I know it was downloaded directly from dataset. I want to know what does the data mean in this file and I looked up a lot of information but didn't find a solution. Can u answer it for me ?
Looking for your reply. Thanks again

**Comment by yongqyu** [comment]
Hi verds.
I think you should refer to this paper.
[Recognizing Actions from Depth Cameras as Weakly Aligned Multi-Part Bag-of-Poses](http://www.micc.unifi.it/seidenari/wp-content/papercite-data/pdf/cvprwks13.pdf)

Ask any questions about my implementation.
Thanks.

**Comment by tiredDi** [comment]
Thank u very much, this paper is very practical for me, but I haven't found any code that can be implemented. Do you have any relevant codes to share with me?
Looking for your reply. Thanks again

**Comment by yongqyu** [comment]
I do not know the existence of relevant code.
I implemented it from zero, too.
Sorry for the late reply.

**Comment by tiredDi** [comment]
To learn from u ,Thanks~
