### ISSUE TITLE
about node features

### ISSUE THREAD

**Issue by liuchanfeng165** [yongqyu/st-gcn-pytorch#3]
Hi @yongqyu , could u tell me about u reason that rebuild node features of  keypoints ?
		self.terminal = nn.Parameter(torch.randn(terminal_cnt, actor_cnt, feat_dims))
		head_la = F.interpolate(torch.stack([self.terminal[0],self.terminal[1]],2), 6)#13-》6 ，下采样
		head_ra = F.interpolate(torch.stack([self.terminal[0],self.terminal[2]],2), 6)
		lw_ra = F.interpolate  (torch.stack([self.terminal[3],self.terminal[4]],2), 6)
		node_features = torch.cat([ #0 1 2  ；
								   (head_la[:,:,:3] + head_ra[:,:,:3])/2,
			# ([1, 13, 3])  # 3*5=15
								   torch.stack( (lw_ra[:,:,2], lw_ra[:,:,1], lw_ra[:,:,0]), 2) ,
								   lw_ra[:,:,3:], head_la[:,:,3:], head_ra[:,:,3:] ] , 2) .to(x)
##Q1
 head_la head_ra  lw_ra , why they all  represent   full node features? what's adequate foundation？ 

##Q2
head_la is combined head(index=0)  and neck(index=1), 
head_ra is combined head(index=0)  and spine(index=2), 
lw_ra is combined Lshoulder(index=3)  and Lelbow(index=4), 
this analysis is right, isnt it?
##Q3
terminal_cnt=5, feat_dims=13；
original code has 15 kps  , rebuild 5 x 3 ( terminal_cnt*3 )=15 dims  .
if  keypoints are 16 and I set them respectively as 4 and 13，I would modify code about 'self.terminal'and 'head_la ,head_ra  ,lw_ra'  then how to do?

Thanks.

**Comment by yongqyu** [comment]
Q1.
Rather than rationale, it was an intuitive way to distinguish between left and right.
So we embed the end node and linearly interpolate the points in between.
Q2.
I do not have the data right now and it is hard to confirm.
You have to guess from the coordinate values. sorry.
I did not understand the question 3. Please explain it again.

Thanks for your interest in my implementation.

**Comment by liuchanfeng165** [comment]
Thanks for u kind  response!
About Q3, I wanna konw how to confirm variable terminal_cnt and feat_dims if original dataset has 16 keypoints not 15 keypoints.

**Comment by yongqyu** [comment]
Since ```terminal_cnt``` is a hyperparameter, you can specify it arbitrarily. 
However, interpolation of intermediate nodes should be calculated according to the terminal configuration.
Since ```feat_dims``` is also a hyperparameter, you need to find out the optimal value experimentally.

**Comment by liuchanfeng165** [comment]
I got it 。so all are definded as rand value for trainig pose estimation to find the optimal value .Thanks!
