### ISSUE TITLE
root node

### ISSUE THREAD

**Issue by tiredDi** [yongqyu/st-gcn-pytorch#4]
Hi
In the paper you mentioned, Figure 3 (d). I have two questions about the determination of the root node. 
Q1: Why set Left Shoulder and Right Knee (green node) as root node 
Q2: Why not set more root node like: Left Shoulder,Right Shoulder,Left Knee,Right Knee.
Looking forward to  your reply 
Thanks ~

**Comment by yongqyu** [comment]
The green node in the figure is an example. 
The same operation is performed on the other nodes. 
This answer is likely to be Q2's answer.
