### ISSUE TITLE
 dynamically modeling these multiple body parts

### ISSUE THREAD

**Issue by tiredDi** [yongqyu/st-gcn-pytorch#5]
Hi, it's me again
In this paper 《Spatial Temporal Graph Convolutional Networks for Skeleton-Based Action Recognition》, it says : " should have different importance in modeling the dynamics of these parts (multiple body parts.). " in section 3.5 
I want to ask which part of the code is dynamically modeling these multiple body parts,and how
Looking forward to your reply
Thank u very very very much

**Comment by yongqyu** [comment]
sorry for late answer.
And please understand that I haven't remembered it long since I did this research.
I think it's part of embedding each end-points differently.
Here is the part of it in my code:

https://github.com/yongqyu/st-gcn-pytorch/blob/master/model.py#L21

Thank you
