### ISSUE TITLE
Training on Custom dataset

### ISSUE THREAD

**Issue by mdshopon** [yongqyu/st-gcn-pytorch#9]
Hello there. Can you kindly please tell how to train on custom dataset? I have some data as the following format
(Data_Size, 55, 25,3) 

When I try to feed the data I get an error from GCNN layer. can you please give me some idea how to resolve this issue?

**Comment by yongqyu** [comment]
Hi, mdshopon.

sorry for late answer.
I also don't have this file and data right now, so I can't confirm it correctly.
However, I think maybe the shape of the input can be known by referring to the following [code](https://github.com/yongqyu/st-gcn-pytorch/blob/master/model.py#L38).
If you still don't know, please try this size (bsz, 10, 45, 3).

Sorry for not being very helpful.
Thanks.
